[gcp_service_account]

type = “service_account”
project_id = “antimicrobial-data-sheet”
private_key_id = “86e9a180a239ae70ec7df52936e6780888fdd6c0”
private_key = “””—–BEGIN PRIVATE KEY—–
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDG3AvgHuRzC3e5
G99a7JeYghfEefM+x6aCQYX0i59w1Qi8XMItnfdfca2dN64cxn4PBxm9VUjdKgfD
xLkgmh6sXEeBa2gHEkfwedvUfzDzBaZYTfnBv0s+B8jn2BTQ31giACWzVlLCpfiB
+TiFr6OHHRgoscuvqRddF+7Uzvbxf9whjQpJl/oz92yzoKVp5vvTNlUWhhiN6hgL
PGKvyAgpUmShc3K0nCHaZmgE4VN/T6LsplMpzfTXdZkZ1XbXjjKGZ2HlIsPTnJh5
GwUOWumzHL1vSsERTaSzfFePgk6DUEaaeguMrYxu+ttWKmikOVoNVRSKZE/hzaQb
ATuW9wD7AgMBAAECggEAN2pkqM0TDng4oc4BnR3nVOmT4/2z6l/Kp+vIf5BVGyVS
rOMQfZPStrdAEVrN21j5EgkBhEB68J7g0Q5GJK6uM4v3pTogIDBY+cuLlhjntCFz
7JG2Muay+hNDSlBt5JMIxVjTKLm6kGGd8eJYfPCoGmPiMpzxTP9K8ndT59vQ9xUT
laOTXh/EEo8htDs6zyYEzborNLpBNAbaQ/YEPgHdXM8YghTv8hwrX/qZKl7uLeAK
XA33k2DENj+GlarSF6bPTYjjzwJfqtafVxbsEngqBElOzAfyQ3Cggn6gtNEYUQkg
ZCWD1Vv0/pal62g/y8YHVYGbg+toluOd1Fdd7CER2QKBgQDqGIbQJKt1C+PhrF65
g2MVSUB5V0cMiD2pOaQSgperyJnllxix3ZpXPuqVa/P9paBggLqQZ7UIdD1HP/KD
rVTYSVPVAsMQ25+Fmqi7W0AHq02M2Zlp6s1uzCW0Pm5xoRuP6OSh3lFDY9Ks7tlq
UWjgjI92V8AS7mNUeYik9iaPdwKBgQDZd3qynTSYTL43JJ/6ThehdvQCT3cIkecp
aDjdo9EX5LAt8n2ZpYKI2X9BQFJZ49uw/VU/OlypSTisKaA6+DJ/pW7szoz3QjFT
/3Qp+QVC4m8yh0W9F/dfj8w6KnZgFbMd3z1bEAz/dWLLgozCxvcQJAFqeu4v040C
Eq/a+FpjnQKBgQDmxh0Izk2Uio8xJzsOiR7BmkAMHuU0zo5y6Bb+BG2+9Hf6pPS8
S2jev3CEszKKB6BN4jmJKCOIXQcX2UubUeGFguw43osscEYXcLsMUE2UAeTmiJE7
oDS7GFfHE5DPRfKk8QOLK15TH/JNdv0wWWcZjpfTI3h/cTDM0y7I6LxkywKBgBCq
3qWX9PMDVsTlMrm9iIQgmN0geBAZFq2OxmT+bEU3iuVKo6PGErYobV9z7ZvkIe9z
yzfYYke7S/OuERDT+xLbfB/8SMOeuCcm+iFJa8TPlBQ8V/UBRD13yQBgRshggWT1
uj8jgMuHlLXiYKWBGGiNSep+V4kk3rbc9cuDo3HlAoGAK/d+VlXN76JBIKEcsEhK
VK5GN1E2Z4P0Lko1yIcdWiBwpCIpF0vbnNo9YDleTWtdzI5slOuYM8A2azPK6qAW
fSPQ7Tv9SKEHgTSL6iqX1lQGBSlxh1j2aMWsJMNUkS7x3vNJ0yY11i9eF+VUXQEw
TOyZJmMk+xx7HSQv9saecjo=
—–END PRIVATE KEY—–”””
client_email = “dseek-data-antimicrobial@antimicrobial-data-sheet.iam.gserviceaccount.com”
client_id = “117493900348644313899”
auth_uri = “https://accounts.google.com/o/oauth2/auth”
token_uri = “https://oauth2.googleapis.com/token”
auth_provider_x509_cert_url = “https://www.googleapis.com/oauth2/v1/certs”
client_x509_cert_url = “https://www.googleapis.com/robot/v1/metadata/x509/dseek-data-antimicrobial%40antimicrobial-data-sheet.iam.gserviceaccount.com”
universe_domain = “googleapis.com”